#!/usr/bin/env bash
#using if statements to create branches in bash scripts

count=1
while [ $count -le 10 ];
do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
