#!/usr/bin/env bash
# creating a clock time witht a bash script

hour=0
minute=1
line=1

while [ $hour -le 12 ]; do
    echo "Hour: $hour"

    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
        ((line++))
    done

    minute=1  # Reset minutes for the next hour
    ((hour++))
done
